# Site Metadata
title: "International Organization for Identity Documents"
description: >
  The International Organization for Identity Documents (OIDI) is established through this Charter to create a global framework for cooperation, coordination, and mutual understanding in the field of identity documents and systems. Secure and verifiable identity management is essential for protecting legal rights, enabling access to services, facilitating international travel, safeguarding public safety, and promoting good governance. The Charter acknowledges the complexity of identity systems, including civil registries, digital credentials, biometrics, and cryptographic infrastructure, and affirms the sovereign authority of states to manage them in accordance with national laws. It highlights the need for a neutral, inclusive, and technically competent international body to guide and harmonize identity standards and practices. In response to challenges such as technological fragmentation, document fraud, and identity theft, OIDI is tasked with fostering interoperability, promoting best practices, supporting capacity building, enabling responsible information exchange, and strengthening trust in global identity infrastructure in alignment with international law and human dignity.

url: "https://int-oid.github.io"
baseurl: ""  

logo: "/flag_b.svg"

author:
  name: "OIDI Secretariat"
  email: "secretariat@oidi.org"

social:
  name: "OIDI"
  links:
    - https://github.com/int-oid
    - https://www.linkedin.com/company/oidi
    - https://github.com/xof955

lang: "en"
locale: "en_US"


markdown: kramdown
theme: minima


plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

google_analytics: ""

exclude:
  - README.md
  - LICENSE
  - .github/

github:
  is_project_page: false  
